export interface DexEntry { id: number; display: string; api: string; cls: string | null; }

// Gen 1 national dex 1-151. cls = classifier class (null = never predicted).
export const DEX151: DexEntry[] = [
  { id: 1, display: 'BULBASAUR', api: 'bulbasaur', cls: 'Bulbasaur' },
  { id: 2, display: 'IVYSAUR', api: 'ivysaur', cls: 'Ivysaur' },
  { id: 3, display: 'VENUSAUR', api: 'venusaur', cls: 'Venusaur' },
  { id: 4, display: 'CHARMANDER', api: 'charmander', cls: 'Charmander' },
  { id: 5, display: 'CHARMELEON', api: 'charmeleon', cls: 'Charmeleon' },
  { id: 6, display: 'CHARIZARD', api: 'charizard', cls: 'Charizard' },
  { id: 7, display: 'SQUIRTLE', api: 'squirtle', cls: 'Squirtle' },
  { id: 8, display: 'WARTORTLE', api: 'wartortle', cls: 'Wartortle' },
  { id: 9, display: 'BLASTOISE', api: 'blastoise', cls: 'Blastoise' },
  { id: 10, display: 'CATERPIE', api: 'caterpie', cls: 'Caterpie' },
  { id: 11, display: 'METAPOD', api: 'metapod', cls: 'Metapod' },
  { id: 12, display: 'BUTTERFREE', api: 'butterfree', cls: 'Butterfree' },
  { id: 13, display: 'WEEDLE', api: 'weedle', cls: 'Weedle' },
  { id: 14, display: 'KAKUNA', api: 'kakuna', cls: 'Kakuna' },
  { id: 15, display: 'BEEDRILL', api: 'beedrill', cls: 'Beedrill' },
  { id: 16, display: 'PIDGEY', api: 'pidgey', cls: 'Pidgey' },
  { id: 17, display: 'PIDGEOTTO', api: 'pidgeotto', cls: 'Pidgeotto' },
  { id: 18, display: 'PIDGEOT', api: 'pidgeot', cls: 'Pidgeot' },
  { id: 19, display: 'RATTATA', api: 'rattata', cls: 'Rattata' },
  { id: 20, display: 'RATICATE', api: 'raticate', cls: 'Raticate' },
  { id: 21, display: 'SPEAROW', api: 'spearow', cls: 'Spearow' },
  { id: 22, display: 'FEAROW', api: 'fearow', cls: 'Fearow' },
  { id: 23, display: 'EKANS', api: 'ekans', cls: 'Ekans' },
  { id: 24, display: 'ARBOK', api: 'arbok', cls: 'Arbok' },
  { id: 25, display: 'PIKACHU', api: 'pikachu', cls: 'Pikachu' },
  { id: 26, display: 'RAICHU', api: 'raichu', cls: 'Raichu' },
  { id: 27, display: 'SANDSHREW', api: 'sandshrew', cls: 'Sandshrew' },
  { id: 28, display: 'SANDSLASH', api: 'sandslash', cls: 'Sandslash' },
  { id: 29, display: 'NIDORAN♀', api: 'nidoran-f', cls: null },
  { id: 30, display: 'NIDORINA', api: 'nidorina', cls: 'Nidorina' },
  { id: 31, display: 'NIDOQUEEN', api: 'nidoqueen', cls: 'Nidoqueen' },
  { id: 32, display: 'NIDORAN♂', api: 'nidoran-m', cls: null },
  { id: 33, display: 'NIDORINO', api: 'nidorino', cls: 'Nidorino' },
  { id: 34, display: 'NIDOKING', api: 'nidoking', cls: 'Nidoking' },
  { id: 35, display: 'CLEFAIRY', api: 'clefairy', cls: 'Clefairy' },
  { id: 36, display: 'CLEFABLE', api: 'clefable', cls: 'Clefable' },
  { id: 37, display: 'VULPIX', api: 'vulpix', cls: 'Vulpix' },
  { id: 38, display: 'NINETALES', api: 'ninetales', cls: 'Ninetales' },
  { id: 39, display: 'JIGGLYPUFF', api: 'jigglypuff', cls: 'Jigglypuff' },
  { id: 40, display: 'WIGGLYTUFF', api: 'wigglytuff', cls: 'Wigglytuff' },
  { id: 41, display: 'ZUBAT', api: 'zubat', cls: 'Zubat' },
  { id: 42, display: 'GOLBAT', api: 'golbat', cls: 'Golbat' },
  { id: 43, display: 'ODDISH', api: 'oddish', cls: 'Oddish' },
  { id: 44, display: 'GLOOM', api: 'gloom', cls: 'Gloom' },
  { id: 45, display: 'VILEPLUME', api: 'vileplume', cls: 'Vileplume' },
  { id: 46, display: 'PARAS', api: 'paras', cls: 'Paras' },
  { id: 47, display: 'PARASECT', api: 'parasect', cls: 'Parasect' },
  { id: 48, display: 'VENONAT', api: 'venonat', cls: 'Venonat' },
  { id: 49, display: 'VENOMOTH', api: 'venomoth', cls: 'Venomoth' },
  { id: 50, display: 'DIGLETT', api: 'diglett', cls: 'Diglett' },
  { id: 51, display: 'DUGTRIO', api: 'dugtrio', cls: 'Dugtrio' },
  { id: 52, display: 'MEOWTH', api: 'meowth', cls: 'Meowth' },
  { id: 53, display: 'PERSIAN', api: 'persian', cls: 'Persian' },
  { id: 54, display: 'PSYDUCK', api: 'psyduck', cls: 'Psyduck' },
  { id: 55, display: 'GOLDUCK', api: 'golduck', cls: 'Golduck' },
  { id: 56, display: 'MANKEY', api: 'mankey', cls: 'Mankey' },
  { id: 57, display: 'PRIMEAPE', api: 'primeape', cls: 'Primeape' },
  { id: 58, display: 'GROWLITHE', api: 'growlithe', cls: 'Growlithe' },
  { id: 59, display: 'ARCANINE', api: 'arcanine', cls: 'Arcanine' },
  { id: 60, display: 'POLIWAG', api: 'poliwag', cls: 'Poliwag' },
  { id: 61, display: 'POLIWHIRL', api: 'poliwhirl', cls: 'Poliwhirl' },
  { id: 62, display: 'POLIWRATH', api: 'poliwrath', cls: 'Poliwrath' },
  { id: 63, display: 'ABRA', api: 'abra', cls: 'Abra' },
  { id: 64, display: 'KADABRA', api: 'kadabra', cls: 'Kadabra' },
  { id: 65, display: 'ALAKAZAM', api: 'alakazam', cls: 'Alakazam' },
  { id: 66, display: 'MACHOP', api: 'machop', cls: 'Machop' },
  { id: 67, display: 'MACHOKE', api: 'machoke', cls: 'Machoke' },
  { id: 68, display: 'MACHAMP', api: 'machamp', cls: 'Machamp' },
  { id: 69, display: 'BELLSPROUT', api: 'bellsprout', cls: 'Bellsprout' },
  { id: 70, display: 'WEEPINBELL', api: 'weepinbell', cls: 'Weepinbell' },
  { id: 71, display: 'VICTREEBEL', api: 'victreebel', cls: 'Victreebel' },
  { id: 72, display: 'TENTACOOL', api: 'tentacool', cls: 'Tentacool' },
  { id: 73, display: 'TENTACRUEL', api: 'tentacruel', cls: 'Tentacruel' },
  { id: 74, display: 'GEODUDE', api: 'geodude', cls: 'Geodude' },
  { id: 75, display: 'GRAVELER', api: 'graveler', cls: 'Graveler' },
  { id: 76, display: 'GOLEM', api: 'golem', cls: 'Golem' },
  { id: 77, display: 'PONYTA', api: 'ponyta', cls: 'Ponyta' },
  { id: 78, display: 'RAPIDASH', api: 'rapidash', cls: 'Rapidash' },
  { id: 79, display: 'SLOWPOKE', api: 'slowpoke', cls: 'Slowpoke' },
  { id: 80, display: 'SLOWBRO', api: 'slowbro', cls: 'Slowbro' },
  { id: 81, display: 'MAGNEMITE', api: 'magnemite', cls: 'Magnemite' },
  { id: 82, display: 'MAGNETON', api: 'magneton', cls: 'Magneton' },
  { id: 83, display: "FARFETCH'D", api: 'farfetchd', cls: 'Farfetchd' },
  { id: 84, display: 'DODUO', api: 'doduo', cls: 'Doduo' },
  { id: 85, display: 'DODRIO', api: 'dodrio', cls: 'Dodrio' },
  { id: 86, display: 'SEEL', api: 'seel', cls: 'Seel' },
  { id: 87, display: 'DEWGONG', api: 'dewgong', cls: 'Dewgong' },
  { id: 88, display: 'GRIMER', api: 'grimer', cls: 'Grimer' },
  { id: 89, display: 'MUK', api: 'muk', cls: 'Muk' },
  { id: 90, display: 'SHELLDER', api: 'shellder', cls: 'Shellder' },
  { id: 91, display: 'CLOYSTER', api: 'cloyster', cls: 'Cloyster' },
  { id: 92, display: 'GASTLY', api: 'gastly', cls: 'Gastly' },
  { id: 93, display: 'HAUNTER', api: 'haunter', cls: 'Haunter' },
  { id: 94, display: 'GENGAR', api: 'gengar', cls: 'Gengar' },
  { id: 95, display: 'ONIX', api: 'onix', cls: 'Onix' },
  { id: 96, display: 'DROWZEE', api: 'drowzee', cls: 'Drowzee' },
  { id: 97, display: 'HYPNO', api: 'hypno', cls: 'Hypno' },
  { id: 98, display: 'KRABBY', api: 'krabby', cls: 'Krabby' },
  { id: 99, display: 'KINGLER', api: 'kingler', cls: 'Kingler' },
  { id: 100, display: 'VOLTORB', api: 'voltorb', cls: 'Voltorb' },
  { id: 101, display: 'ELECTRODE', api: 'electrode', cls: 'Electrode' },
  { id: 102, display: 'EXEGGCUTE', api: 'exeggcute', cls: 'Exeggcute' },
  { id: 103, display: 'EXEGGUTOR', api: 'exeggutor', cls: 'Exeggutor' },
  { id: 104, display: 'CUBONE', api: 'cubone', cls: 'Cubone' },
  { id: 105, display: 'MAROWAK', api: 'marowak', cls: 'Marowak' },
  { id: 106, display: 'HITMONLEE', api: 'hitmonlee', cls: 'Hitmonlee' },
  { id: 107, display: 'HITMONCHAN', api: 'hitmonchan', cls: 'Hitmonchan' },
  { id: 108, display: 'LICKITUNG', api: 'lickitung', cls: 'Lickitung' },
  { id: 109, display: 'KOFFING', api: 'koffing', cls: 'Koffing' },
  { id: 110, display: 'WEEZING', api: 'weezing', cls: 'Weezing' },
  { id: 111, display: 'RHYHORN', api: 'rhyhorn', cls: 'Rhyhorn' },
  { id: 112, display: 'RHYDON', api: 'rhydon', cls: 'Rhydon' },
  { id: 113, display: 'CHANSEY', api: 'chansey', cls: 'Chansey' },
  { id: 114, display: 'TANGELA', api: 'tangela', cls: 'Tangela' },
  { id: 115, display: 'KANGASKHAN', api: 'kangaskhan', cls: 'Kangaskhan' },
  { id: 116, display: 'HORSEA', api: 'horsea', cls: 'Horsea' },
  { id: 117, display: 'SEADRA', api: 'seadra', cls: 'Seadra' },
  { id: 118, display: 'GOLDEEN', api: 'goldeen', cls: 'Goldeen' },
  { id: 119, display: 'SEAKING', api: 'seaking', cls: 'Seaking' },
  { id: 120, display: 'STARYU', api: 'staryu', cls: 'Staryu' },
  { id: 121, display: 'STARMIE', api: 'starmie', cls: 'Starmie' },
  { id: 122, display: 'MR. MIME', api: 'mr-mime', cls: 'MrMime' },
  { id: 123, display: 'SCYTHER', api: 'scyther', cls: 'Scyther' },
  { id: 124, display: 'JYNX', api: 'jynx', cls: 'Jynx' },
  { id: 125, display: 'ELECTABUZZ', api: 'electabuzz', cls: 'Electabuzz' },
  { id: 126, display: 'MAGMAR', api: 'magmar', cls: 'Magmar' },
  { id: 127, display: 'PINSIR', api: 'pinsir', cls: 'Pinsir' },
  { id: 128, display: 'TAUROS', api: 'tauros', cls: 'Tauros' },
  { id: 129, display: 'MAGIKARP', api: 'magikarp', cls: 'Magikarp' },
  { id: 130, display: 'GYARADOS', api: 'gyarados', cls: 'Gyarados' },
  { id: 131, display: 'LAPRAS', api: 'lapras', cls: 'Lapras' },
  { id: 132, display: 'DITTO', api: 'ditto', cls: 'Ditto' },
  { id: 133, display: 'EEVEE', api: 'eevee', cls: 'Eevee' },
  { id: 134, display: 'VAPOREON', api: 'vaporeon', cls: 'Vaporeon' },
  { id: 135, display: 'JOLTEON', api: 'jolteon', cls: 'Jolteon' },
  { id: 136, display: 'FLAREON', api: 'flareon', cls: 'Flareon' },
  { id: 137, display: 'PORYGON', api: 'porygon', cls: 'Porygon' },
  { id: 138, display: 'OMANYTE', api: 'omanyte', cls: 'Omanyte' },
  { id: 139, display: 'OMASTAR', api: 'omastar', cls: 'Omastar' },
  { id: 140, display: 'KABUTO', api: 'kabuto', cls: 'Kabuto' },
  { id: 141, display: 'KABUTOPS', api: 'kabutops', cls: 'Kabutops' },
  { id: 142, display: 'AERODACTYL', api: 'aerodactyl', cls: 'Aerodactyl' },
  { id: 143, display: 'SNORLAX', api: 'snorlax', cls: 'Snorlax' },
  { id: 144, display: 'ARTICUNO', api: 'articuno', cls: 'Articuno' },
  { id: 145, display: 'ZAPDOS', api: 'zapdos', cls: 'Zapdos' },
  { id: 146, display: 'MOLTRES', api: 'moltres', cls: 'Moltres' },
  { id: 147, display: 'DRATINI', api: 'dratini', cls: 'Dratini' },
  { id: 148, display: 'DRAGONAIR', api: 'dragonair', cls: 'Dragonair' },
  { id: 149, display: 'DRAGONITE', api: 'dragonite', cls: 'Dragonite' },
  { id: 150, display: 'MEWTWO', api: 'mewtwo', cls: 'Mewtwo' },
  { id: 151, display: 'MEW', api: 'mew', cls: 'Mew' },
];

export function normDexKey(s: string): string {
  return s.toLowerCase().replace(/[^a-z]/g, '');
}

/** Scanning an evolution also registers its never-predicted base form.
 *  Keys are normDexKey values (nidoran-m -> 'nidoranm', avoids ♂/♀ collision). */
const EVO_SEEN_ALIAS: Record<string, string[]> = {
  nidorino: ['nidoranm'],
  nidorina: ['nidoranf'],
};

export function aliasSeenKeys(prediction: string): string[] {
  return EVO_SEEN_ALIAS[normDexKey(prediction)] ?? [];
}

/** Collector rank by seen count. */
export function dexRank(n: number): string {
  if (n >= 151) return 'MASTER';
  if (n >= 100) return 'VETERAN';
  if (n >= 60) return 'ACE';
  if (n >= 30) return 'RANGER';
  if (n >= 10) return 'TRAINER';
  return 'ROOKIE';
}
